import { DriverRecord } from "../store/types";

/** 404-GO hamkor haydovchilar tarmog'i — boshlang'ich ro'yxat */
export const INITIAL_DRIVER_FLEET: DriverRecord[] = [
  {
    id: "drv-rustam",
    firstName: "Rustam",
    lastName: "Aliyev",
    phone: "+998901234567",
    carName: "Chevrolet Onix",
    carNumber: "01 D 345 AB",
    rating: 4.92,
    trips: 2156,
    serviceTypes: ["taxi"],
    status: "online",
    location: { latitude: 41.3113, longitude: 69.2797 },
    currentOrderId: null,
    verified: true,
  },
  {
    id: "drv-sardor",
    firstName: "Sardor",
    lastName: "Karimov",
    phone: "+998907654321",
    carName: "BYD Song Plus",
    carNumber: "01 A 777 AA",
    rating: 4.88,
    trips: 1847,
    serviceTypes: ["taxi", "delivery"],
    status: "online",
    location: { latitude: 41.3031, longitude: 69.2486 },
    currentOrderId: null,
    verified: true,
  },
  {
    id: "drv-dina",
    firstName: "Dina",
    lastName: "Ahmedova",
    phone: "+998931112233",
    carName: "Kia K5",
    carNumber: "01 B 123 AB",
    rating: 4.95,
    trips: 987,
    serviceTypes: ["taxi"],
    status: "online",
    location: { latitude: 41.3216, longitude: 69.2285 },
    currentOrderId: null,
    verified: true,
  },
  {
    id: "drv-javohir",
    firstName: "Javohir",
    lastName: "Rahimov",
    phone: "+998935556677",
    carName: "Chevrolet Matiz",
    carNumber: "01 P 111 AA",
    rating: 4.89,
    trips: 1104,
    serviceTypes: ["delivery"],
    status: "online",
    location: { latitude: 41.3621, longitude: 69.2821 },
    currentOrderId: null,
    verified: true,
  },
  {
    id: "drv-bahodir",
    firstName: "Bahodir",
    lastName: "Tursunov",
    phone: "+998939998877",
    carName: "Gazelle (1.5t)",
    carNumber: "01 Y 101 AA",
    rating: 4.86,
    trips: 620,
    serviceTypes: ["cargo"],
    status: "online",
    location: { latitude: 41.2225, longitude: 69.2225 },
    currentOrderId: null,
    verified: true,
  },
];
